### ISSUE TITLE
Spelling and Grammar Corrections in Documentation

### ISSUE THREAD

**Issue by munyanezaarmel** [EnAccess/OpenPAYGO-docs#11]
I have reviewed the current documentation and identified several spelling errors and grammatical issues that need correction. These include:

-  Correcting misspellings such as "MITlicense" to "MIT license. ", "feautres " to "Features"

- Improving sentence structure for clarity, such as rephrasing "adds the additional restriction" to "adds an additional restriction."

**Comment by dmohns** [comment]
Hey @munyanezaarmel thank you for reviewing our documentation and your report.

It is true documentation could use some improvement w.r.t. to spelling and grammar. Feel free to send a Pull Request for improvements that you have already noticed. It will be much appreciated!

**Comment by munyanezaarmel** [comment]
@dmohns, I’ve created a PR. Could you please take a look?
